#spring.datasource.url= jdbc:postgresql://localhost:5432/sequencing_run_db
#spring.datasource.username=yan
#spring.datasource.password=##########
#server.error.include-binding-errors=always
#server.error.include-exception=true
#server.error.include-message=always
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
