server:
   port: 8888
spring:
  profiles:
    active: native
  cloud:
     config:
       server:
           native:
              searchLocations: file:///home/yan/IdeaProjects/confsvr/src/main/resources/config/sequencingrunservice,file:///home/yan/IdeaProjects/confsvr/src/main/resources/config/sampleservice

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

